### ISSUE TITLE
Code Review I

### ISSUE THREAD

**Issue by Amanda111** [wwyqianqian/ccnubox_fe#1]
这一次写的真的比之前的有很大的进步了，比heart。还有几个问题：
1、header 的宽度应该是100%
2、有一些height是不用写的  （如   .advantage 上的）
3、以后切图尽量不要留太多空白，不然背景图标的位置比较难调整（导致header的下载二维码和功能概览的图标需要用负margin来调整）
 还感觉重大新功能上线图和文字没有对齐，可以再用background-position调整一下
4、最重要的是：media query好像写了没什么用呀 ，拉了一下窗口好像没什么变化。min-width:400px 也太小了。或许可以这样写：缩小到某个px值时，两边的空白部分直接变小，然后内容部分占满剩下的空间

加油修改咯！

**Comment by wwyqianqian** [comment]
恩恩，收到！谢谢学姐的review😍😎  会继续改的

在 2017年2月27日 上午12:00，Amanda111 <notifications@github.com>写道：
