### ISSUE TITLE
Final Code Review

### ISSUE THREAD

**Issue by zxc0328** [wwyqianqian/ccnubox_fe#2]
+ 所有的图片都要切两倍的，Sketch导出的时候选2X。然后放在本地images文件夹里就行，不用传到图床。
+ 不知道你为什么喜欢设置冗余的高度，一个框需要多少高就是多少高。比如二维码那个框
+ 还有，二维码那个框，左右两个有大部分属性是一样的，这个抽取出来啊。你把类似的情况都检查一遍比如`.content-left`和`.content-right`，这个也没搞。还有很多。
+ 你所有的`display:inline-block`布局貌似都没有在父元素设置`font-size:0`去掉中间的间隙。所以`function-bottom`里面那几个小格子你写的百分比都不一样，如果等分的话宽度就不够了。
+ `.advantage`那里`margin-left`用了10%是什么意思。
+ media query说了不用了就去掉了。
+ `footer-top`专门用来占位？margin不会用吗？
+ `footer-bottom`背景拉伸设置不正确，导致底部有空隙。
+  footer内部应该也是定宽居中的布局，你现在是写死了。你可以试试大屏幕下面是什么效果。

评价CSS写的好不好，最简单的一条就是，实现同样的效果，你用的代码少，你的代码就更好一些。当然这个在编程里面是很普遍的一条。当然CSS也需要考虑很多偏工程的问题，你现在先把最基础的事情做好才行。

**Comment by wwyqianqian** [comment]
THX!!

**Comment by zxc0328** [comment]
1.真的切了两倍的图吗，比如那个安卓的二维码，页面上是100px宽，那就要200px宽的图，我看images里面还是114px宽的，你检查一下。
2.我说要抽出公用的，你真的都检查了吗，至少`.content-left`和`.content-right`没有。是不是你的理解有误差，你抽象的时候要思考一下，不是说看着有属性一样就抽，`inline-block`那个相关的属性其实你可以抽出一个全局的公用class的，所有涉及水平布局的地方都可以用。这是按功能来抽象。当然也有很多其他的抽象维度。
3. footer为什么用了绝对定位？

**Comment by zxc0328** [comment]
尽量不要用中文commit，这样比较不专业233 我们公司有个开源项目，里面都是自己公司的人，但issue里都是用英文233 看着很奇怪吧 但的确算比较专业 毕竟Github是公共的场所 

然后`.DS_Store`这个记得删了

**Comment by wwyqianqian** [comment]
@zxc0328     Commit 10 times this afternoon , and here is my last commit :1st_place_medal: https://github.com/wwyqianqian/ccnubox_fe/commit/10e8ac03284dbbad3ce05bbd84d4fd185c15a805

**Comment by zxc0328** [comment]
1. `font-family`在根元素上设置就可以了，不用到处设置。整个页面的字体都是一样的。那每个元素继承根元素的就可以了。然后你确定你看了我发的那篇字体的文章？你设置字体要照顾到中文英文和不同的操作系统，那篇文章最后明确给了一个`font-family`的比较通用的设置。
2. `display-inline:block`和`vertical-align:top`和`font-size:0`这个可以抽出一个工具class，这个还没有搞
，不懂可以问

其他都可以吧，很棒

**Comment by wwyqianqian** [comment]
@zxc0328   💯  5 times  :  font-family, inline-block, font-size, vertical-align, text-align.
5ec447acaaedbb58da6fcc3e92fa783820f8b7a6
2a55d97430fe4f9b1ac097326b4af866fea7bdeb
3f1a232671b0664e737b25fe68e058d48b92314c
4dc49353fc7f6787f6c893146df040e1b33c80b5
662b61cd487fa6e57b4fcad887c54a74637a6f5d
