### ISSUE TITLE
Code Review For Mobile

### ISSUE THREAD

**Issue by zxc0328** [wwyqianqian/ccnubox_fe#3]
首先，你看一下Network，里面有25个请求。对于移动端页面来说是无法忍受的。要解决这个，可以用雪碧图，也可以用SVG。现在来看SVG是最合适的。雪碧图适合那种要展示大量位图的页面，比如H5。SVG适合icon。所以把所有的图标都换成SVG吧。背景不用。SVG是inline在首页的HTML里面的，所以请求就减少了。

CSS

+ `.content-top`这个很有意思，你有没有发现，子元素的高度超过了父元素。因为你父元素写了`padding`然而在`height`里面没有减掉，也没有设置`box-sizing`。你可能会说，哦哦，这里我没注意。但这里的问题不在于你没注意，在于你没理解BFC里高度的来源。BFC里高度，如果元素本身没有设置，那来源是子元素的高度。**所以你这边父元素压根不用设置高度啊**。这一点我希望你以后不要再忘记了。**好好想一想BFC和IFC下高度和宽度的计算，以后不要写多余的代码，这样很业余的**。
+ `.content-bottom`这里，很奇怪啊，超出父元素了。盒子一个套一个，父元素高度要大于等于子元素。你不按这个常规来的话，有时候会有意向不到的bug。而且如果你是奉行子元素撑开父元素高度的规矩的话，就不会出现这种情况。你这边应该把这个元素放到和顶部的header元素一个等级。然后要和上面重叠的话就搞一个负margin就行。
+ `.inline-block`这个utility的class，为什么不把`vertical-align`放进去呢。因为你这个class是水平居中的功能，水平居中的话一般`inline-block`和`vertical-align`是一起用的。**抽功能类的时候自己要想想这是为了什么啊**。
+ 还有一个小地方，`.header`这里，`background-repeat`的默认值就是`repeat`。要减少冗余代码。新版Chrome（Canary）里可以看[代码覆盖率](https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage)，你可以检查一下你哪些CSS class没有用到。我这里看是有4.7%的代码是冗余的。

**Comment by wwyqianqian** [comment]
9bd3dba0fa0ce4f99d938fb4e2ea9dd4e95c10a6
8f7a94e0ce6681e8cf7edfae8964c5bc959c2821
58b8bc841b8a53d1bc73d876afd1134879507385
836c72530af19a0da7f43c2dc4308d1c13a8b340
6672249b1d1b63b1c318ba8ae0e164f50c862c9e
暂时除了 SVG，其他的都搞好了
